---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1h
  chart:
    spec:
      chart: keycloak
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    ingress:
      enabled: true
      hostname: auth.systechs.net
      path: /
      pathType: Prefix
    proxy: edge
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.systechs.net`) || Host(`www.auth.systechs.net`)
      kind: Rule
      # middlewares:
      #   - name: traefik-security@kubernetescrd
      #     namespace: traefik
      services:
        - name: keycloak
          namespace: keycloak
          port: 80