---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 1m
  chart:
    spec:
      chart: wordpress
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    wordpressEmail: systematic.tech@outlook.com
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      hostname: wordpress.systechs.net
      path: /
      pathType: Prefix
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wordpress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wordpress.systechs.net`)
      kind: Rule
      middlewares:
        - name: traefik-security@kubernetescrd
          namespace: traefik
      services:
        - name: wordpress
          namespace: wordpress
          port: 80